// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSerial(arg1) {
  return window['go']['main']['App']['ConnectSerial'](arg1);
}

export function DetectFT232() {
  return window['go']['main']['App']['DetectFT232']();
}

export function DisconnectSerial() {
  return window['go']['main']['App']['DisconnectSerial']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSerialStatus() {
  return window['go']['main']['App']['GetSerialStatus']();
}

export function GetStreamURL() {
  return window['go']['main']['App']['GetStreamURL']();
}

export function GetVideoStatus() {
  return window['go']['main']['App']['GetVideoStatus']();
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function ListVideoDevices() {
  return window['go']['main']['App']['ListVideoDevices']();
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SendKeyEvent(arg1, arg2) {
  return window['go']['main']['App']['SendKeyEvent'](arg1, arg2);
}

export function SendMouseButton(arg1, arg2) {
  return window['go']['main']['App']['SendMouseButton'](arg1, arg2);
}

export function SendMouseMove(arg1, arg2) {
  return window['go']['main']['App']['SendMouseMove'](arg1, arg2);
}

export function SendMouseScroll(arg1) {
  return window['go']['main']['App']['SendMouseScroll'](arg1);
}

export function SetCaptureResolution(arg1, arg2) {
  return window['go']['main']['App']['SetCaptureResolution'](arg1, arg2);
}

export function SetDeviceIndex(arg1) {
  return window['go']['main']['App']['SetDeviceIndex'](arg1);
}

export function StartVideo() {
  return window['go']['main']['App']['StartVideo']();
}

export function StopVideo() {
  return window['go']['main']['App']['StopVideo']();
}
