// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {video} from '../models';

export function ConnectSerial(arg1:string):Promise<void>;

export function DetectFT232():Promise<string>;

export function DisconnectSerial():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetRemoteClipboard():Promise<string>;

export function GetRemoteDiag():Promise<string>;

export function GetSerialStatus():Promise<string>;

export function GetStreamURL():Promise<string>;

export function GetVideoDiag():Promise<string>;

export function GetVideoFrameCount():Promise<number>;

export function GetVideoStatus():Promise<boolean>;

export function ListSerialPorts():Promise<Array<string>>;

export function ListVideoDevices():Promise<Array<video.VideoDevice>>;

export function SaveConfig():Promise<void>;

export function SendKeyEvent(arg1:string,arg2:boolean):Promise<void>;

export function SendMouseAbs(arg1:number,arg2:number):Promise<void>;

export function SendMouseButton(arg1:number,arg2:boolean):Promise<void>;

export function SendMouseMove(arg1:number,arg2:number):Promise<void>;

export function SendMouseScroll(arg1:number):Promise<void>;

export function SendText(arg1:string,arg2:boolean):Promise<void>;

export function SetCaptureResolution(arg1:number,arg2:number):Promise<void>;

export function SetDevice(arg1:number,arg2:string):Promise<void>;

export function StartVideo():Promise<void>;

export function StopVideo():Promise<void>;
