// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSerial(arg1) {
  return window['go']['main']['App']['ConnectSerial'](arg1);
}

export function DetectSerialPort() {
  return window['go']['main']['App']['DetectSerialPort']();
}

export function DisconnectSerial() {
  return window['go']['main']['App']['DisconnectSerial']();
}

export function GetAudioDiag() {
  return window['go']['main']['App']['GetAudioDiag']();
}

export function GetAudioMuted() {
  return window['go']['main']['App']['GetAudioMuted']();
}

export function GetAudioVolume() {
  return window['go']['main']['App']['GetAudioVolume']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRemoteClipboard() {
  return window['go']['main']['App']['GetRemoteClipboard']();
}

export function GetRemoteDiag() {
  return window['go']['main']['App']['GetRemoteDiag']();
}

export function GetSerialStatus() {
  return window['go']['main']['App']['GetSerialStatus']();
}

export function GetStreamURL() {
  return window['go']['main']['App']['GetStreamURL']();
}

export function GetVideoDiag() {
  return window['go']['main']['App']['GetVideoDiag']();
}

export function GetVideoFrameCount() {
  return window['go']['main']['App']['GetVideoFrameCount']();
}

export function GetVideoStatus() {
  return window['go']['main']['App']['GetVideoStatus']();
}

export function ListAudioDevices() {
  return window['go']['main']['App']['ListAudioDevices']();
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function ListVideoDevices() {
  return window['go']['main']['App']['ListVideoDevices']();
}

export function MarkSentToRemote(arg1) {
  return window['go']['main']['App']['MarkSentToRemote'](arg1);
}

export function ResolveClipboardForPaste() {
  return window['go']['main']['App']['ResolveClipboardForPaste']();
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SendKeyEvent(arg1, arg2) {
  return window['go']['main']['App']['SendKeyEvent'](arg1, arg2);
}

export function SendMouseAbs(arg1, arg2) {
  return window['go']['main']['App']['SendMouseAbs'](arg1, arg2);
}

export function SendMouseButton(arg1, arg2) {
  return window['go']['main']['App']['SendMouseButton'](arg1, arg2);
}

export function SendMouseMove(arg1, arg2) {
  return window['go']['main']['App']['SendMouseMove'](arg1, arg2);
}

export function SendMouseScroll(arg1) {
  return window['go']['main']['App']['SendMouseScroll'](arg1);
}

export function SendText(arg1, arg2) {
  return window['go']['main']['App']['SendText'](arg1, arg2);
}

export function SetAudioDevice(arg1) {
  return window['go']['main']['App']['SetAudioDevice'](arg1);
}

export function SetAudioMuted(arg1) {
  return window['go']['main']['App']['SetAudioMuted'](arg1);
}

export function SetAudioSampleRate(arg1) {
  return window['go']['main']['App']['SetAudioSampleRate'](arg1);
}

export function SetAudioVolume(arg1) {
  return window['go']['main']['App']['SetAudioVolume'](arg1);
}

export function SetCaptureResolution(arg1, arg2) {
  return window['go']['main']['App']['SetCaptureResolution'](arg1, arg2);
}

export function SetDevice(arg1, arg2) {
  return window['go']['main']['App']['SetDevice'](arg1, arg2);
}

export function StartVideo() {
  return window['go']['main']['App']['StartVideo']();
}

export function StopVideo() {
  return window['go']['main']['App']['StopVideo']();
}

export function TestClipboardPipeline() {
  return window['go']['main']['App']['TestClipboardPipeline']();
}

export function WriteRemoteClipToHost(arg1) {
  return window['go']['main']['App']['WriteRemoteClipToHost'](arg1);
}
